### ISSUE TITLE
Missing config.jelly

### ISSUE THREAD

**Issue by jglick** [fabric8io/fabric8-jenkins-workflow-steps#2]
As a rule, `Step`s should have associated `config.jelly` views with some databinding controls, e.g.

``` xml
<f:entry field="message" title="Message">
    <f:textbox/>
</f:entry>
```

This allows the user to see how to configure them via _Snippet Generator_.

**Comment by jstrachan** [comment]
aha! I was wondering how that worked - many thanks!
